services:
  postgres:
    image: postgres:16
    container_name: nest_postgres_db
    restart: always
    environment:
      # Docker Compose sẽ tự động thay thế các giá trị từ file .env
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      # Bạn cũng có thể dùng biến cho port nếu muốn
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
